# Generated by Django 3.2.12 on 2024-02-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morning', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('professor', models.CharField(max_length=20)),
            ],
        ),
    ]
